# Generated by Django 6.0 on 2025-12-22 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0002_alter_region_name_alter_region_prefix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('for_year', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anual_plan', to='area.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anual_plan', to='area.region')),
            ],
            options={
                'verbose_name': 'Yillik reja',
                'verbose_name_plural': 'Yillik rejalar',
            },
        ),
        migrations.CreateModel(
            name='AnnualPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plan.annualplan')),
            ],
            options={
                'verbose_name': 'Yillik reja bandi',
                'verbose_name_plural': 'Yillik reja bandlari',
            },
        ),
        migrations.CreateModel(
            name='AnnualPlanItemMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'), (5, 'May'), (6, 'Iyun'), (7, 'Iyul'), (8, 'Avgust'), (9, 'Sentabr'), (10, 'Oktabr'), (11, 'Noyabr'), (12, 'Dekabr')], verbose_name='Oy')),
                ('quantity', models.FloatField(verbose_name='Miqdori')),
                ('summa', models.FloatField(verbose_name='Summasi')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plan.annualplanitem')),
            ],
            options={
                'verbose_name': 'Oylik reja ',
                'verbose_name_plural': 'Oylik rejalar',
                'ordering': ['month'],
            },
        ),
        migrations.AddIndex(
            model_name='annualplan',
            index=models.Index(fields=['region', 'district'], name='plan_annual_region__678d41_idx'),
        ),
        migrations.AddIndex(
            model_name='annualplan',
            index=models.Index(fields=['for_year'], name='plan_annual_for_yea_f549ed_idx'),
        ),
        migrations.AddIndex(
            model_name='annualplanitem',
            index=models.Index(fields=['name'], name='plan_annual_name_db4e17_idx'),
        ),
        migrations.AddIndex(
            model_name='annualplanitem',
            index=models.Index(fields=['is_approved'], name='plan_annual_is_appr_b91cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='annualplanitem',
            index=models.Index(fields=['annual_plan'], name='plan_annual_annual__fbf7f2_idx'),
        ),
        migrations.AddIndex(
            model_name='annualplanitemmonth',
            index=models.Index(fields=['item', 'month'], name='plan_annual_item_id_ed4eca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='annualplanitemmonth',
            unique_together={('item', 'month')},
        ),
    ]
