# Generated by Django 5.2.9 on 2025-12-24 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualplanitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='measurement.unit'),
        ),
        migrations.AddField(
            model_name='annualplanitemmonth',
            name='price',
            field=models.FloatField(default=0, verbose_name='Narxi'),
            preserve_default=False,
        ),
    ]
