# Generated by Django 6.0 on 2025-12-22 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('prefix', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'indexes': [models.Index(fields=['name'], name='area_region_name_641165_idx'), models.Index(fields=['prefix'], name='area_region_prefix_d45d3f_idx')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='area.region')),
            ],
            options={
                'verbose_name': 'Tauman',
                'verbose_name_plural': 'Tumanlar',
                'indexes': [models.Index(fields=['name'], name='area_distri_name_8db471_idx')],
                'constraints': [models.UniqueConstraint(fields=('region', 'name'), name='area_unique_region_name')],
            },
        ),
    ]
