# Generated by Django 6.0 on 2025-12-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='prefix',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['prefix'], name='area_region_prefix_d45d3f_idx'),
        ),
    ]
