# Generated by Django 5.2.9 on 2025-12-23 08:16

import django.db.models.deletion
import django.utils.timezone
import utils.common.path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=200)),
                ('file_doc', models.FileField(blank=True, null=True, upload_to=utils.common.path.appeal_letter_doc_upload_path)),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to=utils.common.path.appeal_letter_pdf_upload_path)),
                ('is_approved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='AppealLetterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appeal_letter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appeal.appealletter')),
                ('price_analysis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.priceanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='AppealLetterSigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('purpose', models.CharField(choices=[('signing', 'Imzolash'), ('approval', 'Kelishish')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('signed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('appeal_letter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appeal.appealletter')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.employee')),
                ('price_analysis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.priceanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='appealletter',
            index=models.Index(fields=['-created_at'], name='appeal_appe_created_cdabda_idx'),
        ),
        migrations.AddIndex(
            model_name='appealletter',
            index=models.Index(fields=['-updated_at'], name='appeal_appe_updated_345380_idx'),
        ),
        migrations.AddIndex(
            model_name='appealletteritem',
            index=models.Index(fields=['-created_at'], name='appeal_appe_created_59af35_idx'),
        ),
        migrations.AddIndex(
            model_name='appealletteritem',
            index=models.Index(fields=['-updated_at'], name='appeal_appe_updated_978fff_idx'),
        ),
        migrations.AddIndex(
            model_name='appeallettersigned',
            index=models.Index(fields=['-created_at'], name='appeal_appe_created_d56fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='appeallettersigned',
            index=models.Index(fields=['-updated_at'], name='appeal_appe_updated_6d8877_idx'),
        ),
    ]
