# Generated by Django 5.2.9 on 2025-12-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeallettersigned',
            name='purpose',
            field=models.CharField(choices=[('signatory', 'Imzolovchi'), ('approver', 'Kelishuvchi'), ('performer', 'Ijrochi')], max_length=20),
        ),
    ]
