# Generated by Django 6.0 on 2025-12-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Xarid turi',
                'verbose_name_plural': 'Xarid turlari',
                'indexes': [models.Index(fields=['name'], name='purchase_pu_name_7b82b1_idx')],
            },
        ),
    ]
