# Generated by Django 6.0 on 2025-12-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deliverycondition',
            index=models.Index(fields=['name'], name='delivery_de_name_28c522_idx'),
        ),
    ]
