# Generated by Django 5.2.9 on 2025-12-23 08:16

import django.db.models.deletion
import django.utils.timezone
import utils.common.path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0002_alter_district_options'),
        ('measurement', '0001_initial'),
        ('plan', '0001_initial'),
        ('product', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('incoming_number', models.CharField(max_length=255, unique=True)),
                ('outgoing_number', models.CharField(max_length=255, unique=True)),
                ('incoming_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('outgoing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('communication_type', models.CharField(choices=[('district', 'Tumandan'), ('region', 'Viloyatdan'), ('republic', 'Respublikadan'), ('komplektasiya', 'Komplektasiyadan')], max_length=20)),
                ('direction', models.CharField(blank=True, max_length=255, null=True)),
                ('order_type', models.CharField(choices=[('incoming', 'Kiruvchi'), ('outgoing', 'Chiquvchi')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('is_cancel', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='area.district')),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='staff.employee')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='area.region')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='staff.employee')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(choices=[('signatory', 'Imzolovchi'), ('approver', 'Kelishuvchi'), ('performer', 'Ijrochi')], max_length=25)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to=utils.common.path.attachment_upload_path)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='measurement.category')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PostedWebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=utils.common.path.posted_upload_path)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_product_type', models.CharField(choices=[('outside_annual_plan', 'Yillik rejadan tashqari'), ('annual_plan', 'Yillik reja'), ('service', 'Xizmat')], max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.FloatField()),
                ('comment', models.TextField(blank=True)),
                ('price_analysis_quantity', models.FloatField(default=0)),
                ('annual_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.annualplan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.productmodel')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.producttype')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='measurement.size')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='measurement.unit')),
                ('posted_website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.postedwebsite')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=255)),
                ('employee', models.ManyToManyField(to='staff.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='WordOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=utils.common.path.word_order_upload_path)),
                ('is_approved', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='measurement.category')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='SignedWordOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file_doc', models.FileField(blank=True, null=True, upload_to=utils.common.path.signed_word_order_upload_path)),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to=utils.common.path.signed_pdf_order_upload_path)),
                ('qr_data', models.CharField(blank=True, max_length=300, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.employee')),
                ('word_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.wordorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_seen'], name='orders_orde_is_seen_9ef1b1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_cancel'], name='orders_orde_is_canc_1f69f9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type'], name='orders_orde_order_t_d697ad_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_approved'], name='orders_orde_is_appr_6d98ea_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['incoming_number'], name='orders_orde_incomin_27e5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['outgoing_number'], name='orders_orde_outgoin_3e69ed_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['sender', 'receiver'], name='orders_orde_sender__db766c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['region', 'district'], name='orders_orde_region__96bec5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['communication_type'], name='orders_orde_communi_83e968_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['incoming_date', 'outgoing_date'], name='orders_orde_incomin_351d18_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['communication_type', 'order_type'], name='orders_orde_communi_ecb413_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['outgoing_number', 'incoming_number'], name='orders_orde_outgoin_2cde93_idx'),
        ),
        migrations.AddIndex(
            model_name='officer',
            index=models.Index(fields=['-created_at'], name='orders_offi_created_fdf1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='officer',
            index=models.Index(fields=['-updated_at'], name='orders_offi_updated_ada97c_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['-created_at'], name='orders_atta_created_50f676_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['-updated_at'], name='orders_atta_updated_326681_idx'),
        ),
        migrations.AddIndex(
            model_name='postedwebsite',
            index=models.Index(fields=['-created_at'], name='orders_post_created_47eb35_idx'),
        ),
        migrations.AddIndex(
            model_name='postedwebsite',
            index=models.Index(fields=['-updated_at'], name='orders_post_updated_d6c328_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['-created_at'], name='orders_orde_created_78bb6d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['-updated_at'], name='orders_orde_updated_3e553c_idx'),
        ),
        migrations.AddIndex(
            model_name='statusorder',
            index=models.Index(fields=['-created_at'], name='orders_stat_created_deb0cb_idx'),
        ),
        migrations.AddIndex(
            model_name='statusorder',
            index=models.Index(fields=['-updated_at'], name='orders_stat_updated_ff7ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='wordorder',
            index=models.Index(fields=['-created_at'], name='orders_word_created_a90e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='wordorder',
            index=models.Index(fields=['-updated_at'], name='orders_word_updated_4998b8_idx'),
        ),
        migrations.AddIndex(
            model_name='signedwordorder',
            index=models.Index(fields=['-created_at'], name='orders_sign_created_167ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='signedwordorder',
            index=models.Index(fields=['-updated_at'], name='orders_sign_updated_2c3504_idx'),
        ),
    ]
