# Generated by Django 6.0 on 2025-12-22 12:50

import apps.profiles.staff.path
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('organization', '0001_initial'),
        ('warebank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=400, verbose_name='F.I.O')),
                ('inn', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="INN 14 ta raqamdan iborat bo'lishi kerak", regex='^\\d{14}$')], verbose_name='INN')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon: +998901234567 formatida bo'lishi kerak", regex='^\\+998\\d{9}$')], verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('passport_series', models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Passport seriyasi 2 ta bosh harf (AB, AC)', regex='^[A-Z]{2}$')], verbose_name='Passport seriyasi')),
                ('passport_number', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Passport raqami 7 ta raqamdan iborat', regex='^\\d{7}$')], verbose_name='Passport raqami')),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to=apps.profiles.staff.path.employee_image_upload_path, verbose_name='Passport nusxasi')),
                ('jshshr', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="JSHSHIR 14 ta raqamdan iborat bo'lishi kerak", regex='^\\d{14}$')], verbose_name='JSHSHIR')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.department')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='area.district')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.position')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='area.region')),
                ('warehouse', models.ManyToManyField(blank=True, to='warebank.warehouse')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'indexes': [models.Index(fields=['full_name'], name='staff_emplo_full_na_c7bd9d_idx'), models.Index(fields=['inn', 'jshshr'], name='staff_emplo_inn_215fcb_idx'), models.Index(fields=['region', 'district'], name='staff_emplo_region__9db008_idx'), models.Index(fields=['department', 'position'], name='staff_emplo_departm_895cbb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('phone__isnull', False), models.Q(('phone', ''), _negated=True)), fields=('phone',), name='employee_phone_unique'), models.UniqueConstraint(condition=models.Q(('inn__isnull', False), models.Q(('inn', ''), _negated=True)), fields=('inn',), name='employee_inn_unique'), models.UniqueConstraint(condition=models.Q(('jshshr__isnull', False), models.Q(('jshshr', ''), _negated=True)), fields=('jshshr',), name='employee_jshshr_unique')],
            },
        ),
    ]
