# Generated by Django 6.0 on 2025-12-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('warebank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='warehouse',
            field=models.ManyToManyField(blank=True, to='warebank.warehouse'),
        ),
    ]
