# Generated by Django 5.2.9 on 2025-12-23 08:16

import django.db.models.deletion
import django.utils.timezone
import utils.common.path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0002_deliverycondition_delivery_de_name_28c522_idx'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.CharField(max_length=300)),
                ('stir', models.CharField(max_length=20)),
                ('delivery_day', models.IntegerField()),
                ('org_info', models.FileField(blank=True, null=True, upload_to=utils.common.path.org_info_upload_path)),
                ('stat', models.FileField(blank=True, null=True, upload_to=utils.common.path.stat_upload_path)),
                ('file', models.FileField(blank=True, null=True, upload_to=utils.common.path.tk_file_upload_path)),
                ('delivery_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.deliverycondition')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
                'indexes': [models.Index(fields=['-created_at'], name='commercial__created_a29219_idx'), models.Index(fields=['-updated_at'], name='commercial__updated_2ed7d5_idx')],
            },
        ),
    ]
