# Generated by Django 5.2.9 on 2025-12-24 13:58

import apps.profiles.account.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profil_account', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.profiles.account.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='staff.employee'),
        ),
        migrations.AddField(
            model_name='user',
            name='language_code',
            field=models.CharField(choices=[(
                'uz', "O'zbek tili"), ('ru', 'Rus tili'), ('en', 'English')], default='uz', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('district', 'Tuman'), ('region', 'Viloyat'), (
                'republic', 'Respublika'), ('purchaser', 'Komplektasiya')], default='district', max_length=50),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['role'], name='profil_acco_role_8ecdf9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['language_code'], name='profil_acco_languag_b7aa65_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(
                fields=('employee',), name='user_employee_unique'),
        ),
    ]
