# Generated by Django 5.2.9 on 2025-12-24 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil_account', '0002_alter_user_managers_user_employee_user_language_code_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.employee'),
        ),
    ]
