# Generated by Django 5.2.9 on 2025-12-24 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil_account', '0003_alter_user_employee'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.employee', verbose_name="Foydalanuvchiga bog'langan xodim"),
        ),
        migrations.AlterField(
            model_name='user',
            name='language_code',
            field=models.CharField(choices=[('uz', "O'zbek tili"), ('ru', 'Rus tili'), ('en', 'English')], default='uz', max_length=2, verbose_name='Foydalanuvchi tilini tanlang'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('district', 'Tuman'), ('region', 'Viloyat'), ('republic', 'Respublika'), ('purchaser', 'Komplektasiya')], default='district', max_length=50, verbose_name='Foydalanuvchi turi'),
        ),
    ]
