# Generated by Django 5.2.9 on 2025-12-24 14:08

import apps.profiles.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil_account', '0004_alter_user_employee_alter_user_language_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_/space only.', max_length=150, unique=True, validators=[apps.profiles.account.models.MyUsernameValidator()], verbose_name='username'),
        ),
    ]
