# Generated by Django 6.0 on 2025-12-22 13:06

import django.db.models.deletion
import utils.common.path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurement', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=utils.common.path.template_upload_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measurement.category')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='staff.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
                'indexes': [models.Index(fields=['-created_at'], name='template_template_created_idx'), models.Index(fields=['-updated_at'], name='template_template_updated_idx')],
            },
        ),
    ]
