# Generated by Django 5.2.9 on 2025-12-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='template',
            new_name='template_te_created_32e7e7_idx',
            old_name='template_template_created_idx',
        ),
        migrations.RenameIndex(
            model_name='template',
            new_name='template_te_updated_b0b859_idx',
            old_name='template_template_updated_idx',
        ),
    ]
