# Generated by Django 5.2.9 on 2025-12-24 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('template', '0002_rename_template_template_created_idx_template_te_created_32e7e7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='staff.employee'),
        ),
    ]
