# Generated by Django 5.2.9 on 2025-12-23 08:16

import django.db.models.deletion
import django.utils.timezone
import utils.common.path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAnalysisCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PriceAnalysisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PriceAnalysisSigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('signed_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PriceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=utils.common.path.price_analysis_upload_path)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
            },
        ),
    ]
