# Generated by Django 5.2.9 on 2025-12-23 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceanalysiscommercial',
            name='commercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commercial.commercial'),
        ),
        migrations.AddField(
            model_name='priceanalysiscommercial',
            name='price_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.priceanalysis'),
        ),
        migrations.AddField(
            model_name='priceanalysisitem',
            name='commercial_item',
            field=models.ManyToManyField(blank=True, to='analysis.priceanalysiscommercial'),
        ),
    ]
