# Generated by Django 5.2.9 on 2025-12-23 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0002_initial'),
        ('orders', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceanalysisitem',
            name='order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderproduct'),
        ),
        migrations.AddField(
            model_name='priceanalysisitem',
            name='price_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.priceanalysis'),
        ),
        migrations.AddField(
            model_name='priceanalysissigned',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.employee'),
        ),
        migrations.AddField(
            model_name='priceanalysissigned',
            name='price_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.priceanalysis'),
        ),
        migrations.AddIndex(
            model_name='priceanalysis',
            index=models.Index(fields=['-created_at'], name='analysis_pr_created_12aed0_idx'),
        ),
        migrations.AddIndex(
            model_name='priceanalysis',
            index=models.Index(fields=['-updated_at'], name='analysis_pr_updated_6b864d_idx'),
        ),
        migrations.AddIndex(
            model_name='priceanalysiscommercial',
            index=models.Index(fields=['-created_at'], name='analysis_pr_created_6d19e1_idx'),
        ),
        migrations.AddIndex(
            model_name='priceanalysiscommercial',
            index=models.Index(fields=['-updated_at'], name='analysis_pr_updated_d13dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='priceanalysisitem',
            index=models.Index(fields=['-created_at'], name='analysis_pr_created_b1d38f_idx'),
        ),
        migrations.AddIndex(
            model_name='priceanalysisitem',
            index=models.Index(fields=['-updated_at'], name='analysis_pr_updated_487208_idx'),
        ),
        migrations.AddIndex(
            model_name='priceanalysissigned',
            index=models.Index(fields=['-created_at'], name='analysis_pr_created_bc13d0_idx'),
        ),
        migrations.AddIndex(
            model_name='priceanalysissigned',
            index=models.Index(fields=['-updated_at'], name='analysis_pr_updated_db95f9_idx'),
        ),
    ]
