# Generated by Django 5.2.9 on 2025-12-23 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appeal', '0001_initial'),
        ('product', '0001_initial'),
        ('staff', '0001_initial'),
        ('warebank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseTypeBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=255)),
                ('balance', models.FloatField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warebank.bank')),
                ('purchase_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.producttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PurchaseTypeBankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_type', models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim')], max_length=25)),
                ('summa', models.FloatField()),
                ('appeal_letter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appeal.appealletter')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.employee')),
                ('purchase_type_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_purchase.purchasetypebank')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='purchasetypebank',
            index=models.Index(fields=['-created_at'], name='doc_purchas_created_c38907_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasetypebank',
            index=models.Index(fields=['-updated_at'], name='doc_purchas_updated_76d54c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasetypebankitem',
            index=models.Index(fields=['-created_at'], name='doc_purchas_created_b024f0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasetypebankitem',
            index=models.Index(fields=['-updated_at'], name='doc_purchas_updated_4664d5_idx'),
        ),
    ]
