# Generated by Django 6.0 on 2025-12-21 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0002_alter_region_name_alter_region_prefix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mfo', models.CharField(max_length=50)),
                ('stir', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('site_url', models.CharField(blank=True, max_length=255, null=True)),
                ('geolocation', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='area.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='area.region')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banklar',
                'indexes': [models.Index(fields=['name'], name='warebank_ba_name_bd70cc_idx'), models.Index(fields=['phone'], name='warebank_ba_phone_ac2747_idx'), models.Index(fields=['name', 'stir'], name='warebank_ba_name_532f57_idx'), models.Index(fields=['mfo', 'stir'], name='warebank_ba_mfo_3fcbb4_idx'), models.Index(fields=['region', 'district'], name='warebank_ba_region__558692_idx')],
            },
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='area.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='area.region')),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Omborlar',
                'indexes': [models.Index(fields=['name'], name='warebank_wa_name_5d1241_idx'), models.Index(fields=['phone'], name='warebank_wa_phone_d5e51b_idx'), models.Index(fields=['region', 'district'], name='warebank_wa_region__36a2c6_idx')],
            },
        ),
    ]
